name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm install
          sudo npm install @electron-forge/cli@^6.0.4 @electron-forge/maker-deb@^6.0.4 @electron-forge/maker-rpm@^6.0.4 @electron-forge/maker-squirrel@^6.0.4 @electron-forge/maker-zip@^6.0.4 electron@^22.0.0 electron-builder@^23.6.0 electron-packager@^17.1.1
          npm install electron-squirrel-startup
          npm ci

      - name: Build Mac x64
        run: |
          npm run package-mac
        env:
          CI: true

      - name: Build Mac arm
        run: |
          npm run package-mac-arm64
        env:
          CI: true

      - name: Build Win64
        run: |
          npm run package-win
        env:
          CI: true

      - name: Publish to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          name: app-package
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-package

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: dist/*
          asset_name: app-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip
