on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Build Mac x64
        run: |
          npm run package-mac
        env:
          CI: true

      - name: Build Mac arm64
        run: |
          npm run package-mac-arm64
        env:
          CI: true

      - name: Package app into zip
        run: |
          zip -r app-Botw-Savediter.zip dist

      - name: Publish to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          name: app-package
          path: app-Botw-Savediter.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-package

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: botw_savediter_app_${{ env.GITHUB_SHA }}
          release_name: Release botw_savediter_app
          draft: false
          prerelease: false
          upload_url: ${{ secrets.UPLOAD_URL }}
          asset_path: app-Botw-Savediter.zip
          asset_name: app-Botw-Savediter.zip
          asset_content_type: application/zip
